apiVersion: v1
kind: Secret
metadata:
  name: blog-backend-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo-service:{{ .Values.mongo.port }}/{{ .Values.mongo.database }}"
  PORT: {{ .Values.app.port | quote }}